# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Create_Job_Criteria_UI.ui',
# licensing of 'Create_Job_Criteria_UI.ui' applies.
#
# Created: Thu May  2 15:46:47 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(463, 650)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(140, 40, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 180, 31, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(200, 180, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(40, 260, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(40, 230, 61, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(20, 200, 431, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(40, 290, 91, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(40, 150, 101, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(40, 360, 201, 16))
        self.label_10.setObjectName("label_10")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(40, 380, 351, 51))
        self.textEdit.setObjectName("textEdit")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(40, 440, 81, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(40, 470, 81, 16))
        self.label_12.setObjectName("label_12")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(150, 550, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.warning_label = QtWidgets.QLabel(Form)
        self.warning_label.setGeometry(QtCore.QRect(70, 550, 311, 20))
        self.warning_label.setText("")
        self.warning_label.setObjectName("warning_label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(150, 120, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 150, 291, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(70, 180, 113, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(260, 180, 181, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(110, 260, 113, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(110, 230, 113, 22))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(140, 290, 31, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(230, 290, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.comboBox_4 = QtWidgets.QComboBox(Form)
        self.comboBox_4.setGeometry(QtCore.QRect(190, 290, 31, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(180, 290, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(290, 290, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(250, 290, 31, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(Form)
        self.comboBox_5.setGeometry(QtCore.QRect(300, 290, 31, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(Form)
        self.comboBox_3.setGeometry(QtCore.QRect(120, 440, 181, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.lineEdit_7 = QtWidgets.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(120, 470, 271, 22))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(40, 330, 81, 16))
        self.label_13.setObjectName("label_13")
        self.comboBox_6 = QtWidgets.QComboBox(Form)
        self.comboBox_6.setGeometry(QtCore.QRect(130, 330, 73, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Create Job", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "Company name :", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "Tel :", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "Website :", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "Salary   :", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Form", "Position :", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Form", "_____________________________________________________________", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Form", "Working hour :   :", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Form", "Address            :", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Form", "Short description (150 characters)", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Form", "Education   :", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("Form", "Experience :", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("Form", "confirm", None, -1))
        self.comboBox.setItemText(0, QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.comboBox.setItemText(1, QtWidgets.QApplication.translate("Form", "1", None, -1))
        self.comboBox.setItemText(2, QtWidgets.QApplication.translate("Form", "2", None, -1))
        self.comboBox.setItemText(3, QtWidgets.QApplication.translate("Form", "3", None, -1))
        self.comboBox.setItemText(4, QtWidgets.QApplication.translate("Form", "4", None, -1))
        self.comboBox.setItemText(5, QtWidgets.QApplication.translate("Form", "5", None, -1))
        self.comboBox.setItemText(6, QtWidgets.QApplication.translate("Form", "6", None, -1))
        self.comboBox.setItemText(7, QtWidgets.QApplication.translate("Form", "7", None, -1))
        self.comboBox.setItemText(8, QtWidgets.QApplication.translate("Form", "8", None, -1))
        self.comboBox.setItemText(9, QtWidgets.QApplication.translate("Form", "9", None, -1))
        self.comboBox.setItemText(10, QtWidgets.QApplication.translate("Form", "10", None, -1))
        self.comboBox.setItemText(11, QtWidgets.QApplication.translate("Form", "11", None, -1))
        self.comboBox.setItemText(12, QtWidgets.QApplication.translate("Form", "12", None, -1))
        self.comboBox.setItemText(13, QtWidgets.QApplication.translate("Form", "13", None, -1))
        self.comboBox.setItemText(14, QtWidgets.QApplication.translate("Form", "14", None, -1))
        self.comboBox.setItemText(15, QtWidgets.QApplication.translate("Form", "15", None, -1))
        self.comboBox.setItemText(16, QtWidgets.QApplication.translate("Form", "16", None, -1))
        self.comboBox.setItemText(17, QtWidgets.QApplication.translate("Form", "17", None, -1))
        self.comboBox.setItemText(18, QtWidgets.QApplication.translate("Form", "18", None, -1))
        self.comboBox.setItemText(19, QtWidgets.QApplication.translate("Form", "19", None, -1))
        self.comboBox.setItemText(20, QtWidgets.QApplication.translate("Form", "20", None, -1))
        self.comboBox.setItemText(21, QtWidgets.QApplication.translate("Form", "21", None, -1))
        self.comboBox.setItemText(22, QtWidgets.QApplication.translate("Form", "22", None, -1))
        self.comboBox.setItemText(23, QtWidgets.QApplication.translate("Form", "23", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("Form", "-", None, -1))
        self.comboBox_4.setItemText(0, QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.comboBox_4.setItemText(1, QtWidgets.QApplication.translate("Form", "1", None, -1))
        self.comboBox_4.setItemText(2, QtWidgets.QApplication.translate("Form", "2", None, -1))
        self.comboBox_4.setItemText(3, QtWidgets.QApplication.translate("Form", "3", None, -1))
        self.comboBox_4.setItemText(4, QtWidgets.QApplication.translate("Form", "4", None, -1))
        self.comboBox_4.setItemText(5, QtWidgets.QApplication.translate("Form", "5", None, -1))
        self.comboBox_4.setItemText(6, QtWidgets.QApplication.translate("Form", "6", None, -1))
        self.comboBox_4.setItemText(7, QtWidgets.QApplication.translate("Form", "7", None, -1))
        self.comboBox_4.setItemText(8, QtWidgets.QApplication.translate("Form", "8", None, -1))
        self.comboBox_4.setItemText(9, QtWidgets.QApplication.translate("Form", "9", None, -1))
        self.comboBox_4.setItemText(10, QtWidgets.QApplication.translate("Form", "10", None, -1))
        self.comboBox_4.setItemText(11, QtWidgets.QApplication.translate("Form", "11", None, -1))
        self.comboBox_4.setItemText(12, QtWidgets.QApplication.translate("Form", "12", None, -1))
        self.comboBox_4.setItemText(13, QtWidgets.QApplication.translate("Form", "13", None, -1))
        self.comboBox_4.setItemText(14, QtWidgets.QApplication.translate("Form", "14", None, -1))
        self.comboBox_4.setItemText(15, QtWidgets.QApplication.translate("Form", "15", None, -1))
        self.comboBox_4.setItemText(16, QtWidgets.QApplication.translate("Form", "16", None, -1))
        self.comboBox_4.setItemText(17, QtWidgets.QApplication.translate("Form", "17", None, -1))
        self.comboBox_4.setItemText(18, QtWidgets.QApplication.translate("Form", "18", None, -1))
        self.comboBox_4.setItemText(19, QtWidgets.QApplication.translate("Form", "19", None, -1))
        self.comboBox_4.setItemText(20, QtWidgets.QApplication.translate("Form", "20", None, -1))
        self.comboBox_4.setItemText(21, QtWidgets.QApplication.translate("Form", "21", None, -1))
        self.comboBox_4.setItemText(22, QtWidgets.QApplication.translate("Form", "22", None, -1))
        self.comboBox_4.setItemText(23, QtWidgets.QApplication.translate("Form", "23", None, -1))
        self.comboBox_4.setItemText(24, QtWidgets.QApplication.translate("Form", "24", None, -1))
        self.comboBox_4.setItemText(25, QtWidgets.QApplication.translate("Form", "25", None, -1))
        self.comboBox_4.setItemText(26, QtWidgets.QApplication.translate("Form", "26", None, -1))
        self.comboBox_4.setItemText(27, QtWidgets.QApplication.translate("Form", "27", None, -1))
        self.comboBox_4.setItemText(28, QtWidgets.QApplication.translate("Form", "28", None, -1))
        self.comboBox_4.setItemText(29, QtWidgets.QApplication.translate("Form", "29", None, -1))
        self.comboBox_4.setItemText(30, QtWidgets.QApplication.translate("Form", "30", None, -1))
        self.comboBox_4.setItemText(31, QtWidgets.QApplication.translate("Form", "31", None, -1))
        self.comboBox_4.setItemText(32, QtWidgets.QApplication.translate("Form", "32", None, -1))
        self.comboBox_4.setItemText(33, QtWidgets.QApplication.translate("Form", "33", None, -1))
        self.comboBox_4.setItemText(34, QtWidgets.QApplication.translate("Form", "34", None, -1))
        self.comboBox_4.setItemText(35, QtWidgets.QApplication.translate("Form", "35", None, -1))
        self.comboBox_4.setItemText(36, QtWidgets.QApplication.translate("Form", "36", None, -1))
        self.comboBox_4.setItemText(37, QtWidgets.QApplication.translate("Form", "37", None, -1))
        self.comboBox_4.setItemText(38, QtWidgets.QApplication.translate("Form", "38", None, -1))
        self.comboBox_4.setItemText(39, QtWidgets.QApplication.translate("Form", "39", None, -1))
        self.comboBox_4.setItemText(40, QtWidgets.QApplication.translate("Form", "40", None, -1))
        self.comboBox_4.setItemText(41, QtWidgets.QApplication.translate("Form", "41", None, -1))
        self.comboBox_4.setItemText(42, QtWidgets.QApplication.translate("Form", "42", None, -1))
        self.comboBox_4.setItemText(43, QtWidgets.QApplication.translate("Form", "43", None, -1))
        self.comboBox_4.setItemText(44, QtWidgets.QApplication.translate("Form", "44", None, -1))
        self.comboBox_4.setItemText(45, QtWidgets.QApplication.translate("Form", "45", None, -1))
        self.comboBox_4.setItemText(46, QtWidgets.QApplication.translate("Form", "46", None, -1))
        self.comboBox_4.setItemText(47, QtWidgets.QApplication.translate("Form", "47", None, -1))
        self.comboBox_4.setItemText(48, QtWidgets.QApplication.translate("Form", "48", None, -1))
        self.comboBox_4.setItemText(49, QtWidgets.QApplication.translate("Form", "49", None, -1))
        self.comboBox_4.setItemText(50, QtWidgets.QApplication.translate("Form", "50", None, -1))
        self.comboBox_4.setItemText(51, QtWidgets.QApplication.translate("Form", "51", None, -1))
        self.comboBox_4.setItemText(52, QtWidgets.QApplication.translate("Form", "52", None, -1))
        self.comboBox_4.setItemText(53, QtWidgets.QApplication.translate("Form", "53", None, -1))
        self.comboBox_4.setItemText(54, QtWidgets.QApplication.translate("Form", "54", None, -1))
        self.comboBox_4.setItemText(55, QtWidgets.QApplication.translate("Form", "55", None, -1))
        self.comboBox_4.setItemText(56, QtWidgets.QApplication.translate("Form", "56", None, -1))
        self.comboBox_4.setItemText(57, QtWidgets.QApplication.translate("Form", "57", None, -1))
        self.comboBox_4.setItemText(58, QtWidgets.QApplication.translate("Form", "58", None, -1))
        self.comboBox_4.setItemText(59, QtWidgets.QApplication.translate("Form", "59", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("Form", ":", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("Form", ":", None, -1))
        self.comboBox_2.setItemText(0, QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.comboBox_2.setItemText(1, QtWidgets.QApplication.translate("Form", "1", None, -1))
        self.comboBox_2.setItemText(2, QtWidgets.QApplication.translate("Form", "2", None, -1))
        self.comboBox_2.setItemText(3, QtWidgets.QApplication.translate("Form", "3", None, -1))
        self.comboBox_2.setItemText(4, QtWidgets.QApplication.translate("Form", "4", None, -1))
        self.comboBox_2.setItemText(5, QtWidgets.QApplication.translate("Form", "5", None, -1))
        self.comboBox_2.setItemText(6, QtWidgets.QApplication.translate("Form", "6", None, -1))
        self.comboBox_2.setItemText(7, QtWidgets.QApplication.translate("Form", "7", None, -1))
        self.comboBox_2.setItemText(8, QtWidgets.QApplication.translate("Form", "8", None, -1))
        self.comboBox_2.setItemText(9, QtWidgets.QApplication.translate("Form", "9", None, -1))
        self.comboBox_2.setItemText(10, QtWidgets.QApplication.translate("Form", "10", None, -1))
        self.comboBox_2.setItemText(11, QtWidgets.QApplication.translate("Form", "11", None, -1))
        self.comboBox_2.setItemText(12, QtWidgets.QApplication.translate("Form", "12", None, -1))
        self.comboBox_2.setItemText(13, QtWidgets.QApplication.translate("Form", "13", None, -1))
        self.comboBox_2.setItemText(14, QtWidgets.QApplication.translate("Form", "14", None, -1))
        self.comboBox_2.setItemText(15, QtWidgets.QApplication.translate("Form", "15", None, -1))
        self.comboBox_2.setItemText(16, QtWidgets.QApplication.translate("Form", "16", None, -1))
        self.comboBox_2.setItemText(17, QtWidgets.QApplication.translate("Form", "17", None, -1))
        self.comboBox_2.setItemText(18, QtWidgets.QApplication.translate("Form", "18", None, -1))
        self.comboBox_2.setItemText(19, QtWidgets.QApplication.translate("Form", "19", None, -1))
        self.comboBox_2.setItemText(20, QtWidgets.QApplication.translate("Form", "20", None, -1))
        self.comboBox_2.setItemText(21, QtWidgets.QApplication.translate("Form", "21", None, -1))
        self.comboBox_2.setItemText(22, QtWidgets.QApplication.translate("Form", "22", None, -1))
        self.comboBox_2.setItemText(23, QtWidgets.QApplication.translate("Form", "23", None, -1))
        self.comboBox_5.setItemText(0, QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.comboBox_5.setItemText(1, QtWidgets.QApplication.translate("Form", "1", None, -1))
        self.comboBox_5.setItemText(2, QtWidgets.QApplication.translate("Form", "2", None, -1))
        self.comboBox_5.setItemText(3, QtWidgets.QApplication.translate("Form", "3", None, -1))
        self.comboBox_5.setItemText(4, QtWidgets.QApplication.translate("Form", "4", None, -1))
        self.comboBox_5.setItemText(5, QtWidgets.QApplication.translate("Form", "5", None, -1))
        self.comboBox_5.setItemText(6, QtWidgets.QApplication.translate("Form", "6", None, -1))
        self.comboBox_5.setItemText(7, QtWidgets.QApplication.translate("Form", "7", None, -1))
        self.comboBox_5.setItemText(8, QtWidgets.QApplication.translate("Form", "8", None, -1))
        self.comboBox_5.setItemText(9, QtWidgets.QApplication.translate("Form", "9", None, -1))
        self.comboBox_5.setItemText(10, QtWidgets.QApplication.translate("Form", "10", None, -1))
        self.comboBox_5.setItemText(11, QtWidgets.QApplication.translate("Form", "11", None, -1))
        self.comboBox_5.setItemText(12, QtWidgets.QApplication.translate("Form", "12", None, -1))
        self.comboBox_5.setItemText(13, QtWidgets.QApplication.translate("Form", "13", None, -1))
        self.comboBox_5.setItemText(14, QtWidgets.QApplication.translate("Form", "14", None, -1))
        self.comboBox_5.setItemText(15, QtWidgets.QApplication.translate("Form", "15", None, -1))
        self.comboBox_5.setItemText(16, QtWidgets.QApplication.translate("Form", "16", None, -1))
        self.comboBox_5.setItemText(17, QtWidgets.QApplication.translate("Form", "17", None, -1))
        self.comboBox_5.setItemText(18, QtWidgets.QApplication.translate("Form", "18", None, -1))
        self.comboBox_5.setItemText(19, QtWidgets.QApplication.translate("Form", "19", None, -1))
        self.comboBox_5.setItemText(20, QtWidgets.QApplication.translate("Form", "20", None, -1))
        self.comboBox_5.setItemText(21, QtWidgets.QApplication.translate("Form", "21", None, -1))
        self.comboBox_5.setItemText(22, QtWidgets.QApplication.translate("Form", "22", None, -1))
        self.comboBox_5.setItemText(23, QtWidgets.QApplication.translate("Form", "23", None, -1))
        self.comboBox_5.setItemText(24, QtWidgets.QApplication.translate("Form", "24", None, -1))
        self.comboBox_5.setItemText(25, QtWidgets.QApplication.translate("Form", "25", None, -1))
        self.comboBox_5.setItemText(26, QtWidgets.QApplication.translate("Form", "26", None, -1))
        self.comboBox_5.setItemText(27, QtWidgets.QApplication.translate("Form", "27", None, -1))
        self.comboBox_5.setItemText(28, QtWidgets.QApplication.translate("Form", "28", None, -1))
        self.comboBox_5.setItemText(29, QtWidgets.QApplication.translate("Form", "29", None, -1))
        self.comboBox_5.setItemText(30, QtWidgets.QApplication.translate("Form", "30", None, -1))
        self.comboBox_5.setItemText(31, QtWidgets.QApplication.translate("Form", "31", None, -1))
        self.comboBox_5.setItemText(32, QtWidgets.QApplication.translate("Form", "32", None, -1))
        self.comboBox_5.setItemText(33, QtWidgets.QApplication.translate("Form", "33", None, -1))
        self.comboBox_5.setItemText(34, QtWidgets.QApplication.translate("Form", "34", None, -1))
        self.comboBox_5.setItemText(35, QtWidgets.QApplication.translate("Form", "35", None, -1))
        self.comboBox_5.setItemText(36, QtWidgets.QApplication.translate("Form", "36", None, -1))
        self.comboBox_5.setItemText(37, QtWidgets.QApplication.translate("Form", "37", None, -1))
        self.comboBox_5.setItemText(38, QtWidgets.QApplication.translate("Form", "38", None, -1))
        self.comboBox_5.setItemText(39, QtWidgets.QApplication.translate("Form", "39", None, -1))
        self.comboBox_5.setItemText(40, QtWidgets.QApplication.translate("Form", "40", None, -1))
        self.comboBox_5.setItemText(41, QtWidgets.QApplication.translate("Form", "41", None, -1))
        self.comboBox_5.setItemText(42, QtWidgets.QApplication.translate("Form", "42", None, -1))
        self.comboBox_5.setItemText(43, QtWidgets.QApplication.translate("Form", "43", None, -1))
        self.comboBox_5.setItemText(44, QtWidgets.QApplication.translate("Form", "44", None, -1))
        self.comboBox_5.setItemText(45, QtWidgets.QApplication.translate("Form", "45", None, -1))
        self.comboBox_5.setItemText(46, QtWidgets.QApplication.translate("Form", "46", None, -1))
        self.comboBox_5.setItemText(47, QtWidgets.QApplication.translate("Form", "47", None, -1))
        self.comboBox_5.setItemText(48, QtWidgets.QApplication.translate("Form", "48", None, -1))
        self.comboBox_5.setItemText(49, QtWidgets.QApplication.translate("Form", "49", None, -1))
        self.comboBox_5.setItemText(50, QtWidgets.QApplication.translate("Form", "50", None, -1))
        self.comboBox_5.setItemText(51, QtWidgets.QApplication.translate("Form", "51", None, -1))
        self.comboBox_5.setItemText(52, QtWidgets.QApplication.translate("Form", "52", None, -1))
        self.comboBox_5.setItemText(53, QtWidgets.QApplication.translate("Form", "53", None, -1))
        self.comboBox_5.setItemText(54, QtWidgets.QApplication.translate("Form", "54", None, -1))
        self.comboBox_5.setItemText(55, QtWidgets.QApplication.translate("Form", "55", None, -1))
        self.comboBox_5.setItemText(56, QtWidgets.QApplication.translate("Form", "56", None, -1))
        self.comboBox_5.setItemText(57, QtWidgets.QApplication.translate("Form", "57", None, -1))
        self.comboBox_5.setItemText(58, QtWidgets.QApplication.translate("Form", "58", None, -1))
        self.comboBox_5.setItemText(59, QtWidgets.QApplication.translate("Form", "59", None, -1))
        self.comboBox_3.setItemText(0, QtWidgets.QApplication.translate("Form", "bachelor degree or higher", None, -1))
        self.comboBox_3.setItemText(1, QtWidgets.QApplication.translate("Form", "master degree or higher", None, -1))
        self.comboBox_3.setItemText(2, QtWidgets.QApplication.translate("Form", "PHD", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("Form", "Required Skill", None, -1))
        self.comboBox_6.setItemText(0, QtWidgets.QApplication.translate("Form", "Python", None, -1))
        self.comboBox_6.setItemText(1, QtWidgets.QApplication.translate("Form", "C++/C", None, -1))
        self.comboBox_6.setItemText(2, QtWidgets.QApplication.translate("Form", "JS", None, -1))
        self.comboBox_6.setItemText(3, QtWidgets.QApplication.translate("Form", "HTML/CSS", None, -1))
        self.comboBox_6.setItemText(4, QtWidgets.QApplication.translate("Form", "Java", None, -1))
        self.comboBox_6.setItemText(5, QtWidgets.QApplication.translate("Form", "Dart", None, -1))
        self.comboBox_6.setItemText(6, QtWidgets.QApplication.translate("Form", "Swift", None, -1))
        self.comboBox_6.setItemText(7, QtWidgets.QApplication.translate("Form", "Kotlin", None, -1))
        self.comboBox_6.setItemText(8, QtWidgets.QApplication.translate("Form", "Go", None, -1))
        self.comboBox_6.setItemText(9, QtWidgets.QApplication.translate("Form", "Swift", None, -1))
        self.comboBox_6.setItemText(10, QtWidgets.QApplication.translate("Form", "R", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

