# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Company_Edit_Profile2.ui',
# licensing of 'Company_Edit_Profile2.ui' applies.
#
# Created: Wed May 29 17:24:30 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(759, 645)
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 739, 625))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 4, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 11, 0, 1, 8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_comp_name = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_comp_name.setText("")
        self.lineEdit_comp_name.setObjectName("lineEdit_comp_name")
        self.horizontalLayout.addWidget(self.lineEdit_comp_name)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.lineEdit_city = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_city.setText("")
        self.lineEdit_city.setObjectName("lineEdit_city")
        self.horizontalLayout_9.addWidget(self.lineEdit_city)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 5, 5, 1, 3)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_11.addWidget(self.label_16)
        self.lineEdit_zip = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_zip.setObjectName("lineEdit_zip")
        self.horizontalLayout_11.addWidget(self.lineEdit_zip)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 6, 5, 1, 3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.lineEdit_houseNo = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_houseNo.setObjectName("lineEdit_houseNo")
        self.horizontalLayout_5.addWidget(self.lineEdit_houseNo)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_tel = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_tel.setObjectName("lineEdit_tel")
        self.horizontalLayout_3.addWidget(self.lineEdit_tel)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(98, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_web = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_web.setText("")
        self.lineEdit_web.setObjectName("lineEdit_web")
        self.horizontalLayout_4.addWidget(self.lineEdit_web)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 2, 0, 1, 8)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 9, 0, 1, 7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_comp_logo = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_comp_logo.setObjectName("label_comp_logo")
        self.horizontalLayout_2.addWidget(self.label_comp_logo)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 7, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 0, 1, 1, 2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 0, 3, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 0, 4, 1, 2)
        self.checkBox_5 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 0, 6, 1, 2)
        self.checkBox_7 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout.addWidget(self.checkBox_7, 1, 0, 1, 2)
        self.checkBox_8 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout.addWidget(self.checkBox_8, 1, 2, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout.addWidget(self.checkBox_9, 1, 3, 1, 2)
        self.checkBox_6 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout.addWidget(self.checkBox_6, 1, 5, 1, 2)
        self.checkBox_10 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout.addWidget(self.checkBox_10, 1, 7, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 8, 0, 1, 8)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 13, 7, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_24 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_24.setObjectName("checkBox_24")
        self.gridLayout_2.addWidget(self.checkBox_24, 1, 2, 1, 1)
        self.checkBox_31 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_31.setObjectName("checkBox_31")
        self.gridLayout_2.addWidget(self.checkBox_31, 0, 3, 1, 2)
        self.checkBox_23 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_23.setObjectName("checkBox_23")
        self.gridLayout_2.addWidget(self.checkBox_23, 1, 0, 1, 1)
        self.checkBox_21 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_21.setObjectName("checkBox_21")
        self.gridLayout_2.addWidget(self.checkBox_21, 2, 0, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout_2.addWidget(self.checkBox_17, 0, 2, 1, 1)
        self.checkBox_39 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_39.setObjectName("checkBox_39")
        self.gridLayout_2.addWidget(self.checkBox_39, 3, 1, 1, 1)
        self.checkBox_40 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_40.setObjectName("checkBox_40")
        self.gridLayout_2.addWidget(self.checkBox_40, 3, 3, 1, 1)
        self.checkBox_29 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_29.setObjectName("checkBox_29")
        self.gridLayout_2.addWidget(self.checkBox_29, 2, 1, 1, 1)
        self.checkBox_33 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_33.setObjectName("checkBox_33")
        self.gridLayout_2.addWidget(self.checkBox_33, 2, 2, 1, 1)
        self.checkBox_41 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_41.setObjectName("checkBox_41")
        self.gridLayout_2.addWidget(self.checkBox_41, 3, 2, 1, 1)
        self.checkBox_37 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_37.setObjectName("checkBox_37")
        self.gridLayout_2.addWidget(self.checkBox_37, 2, 3, 1, 2)
        self.checkBox_14 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout_2.addWidget(self.checkBox_14, 0, 0, 1, 1)
        self.checkBox_26 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_26.setObjectName("checkBox_26")
        self.gridLayout_2.addWidget(self.checkBox_26, 1, 3, 1, 2)
        self.checkBox_15 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout_2.addWidget(self.checkBox_15, 0, 1, 1, 1)
        self.checkBox_22 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_22.setObjectName("checkBox_22")
        self.gridLayout_2.addWidget(self.checkBox_22, 1, 1, 1, 1)
        self.checkBox_36 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_36.setObjectName("checkBox_36")
        self.gridLayout_2.addWidget(self.checkBox_36, 3, 0, 1, 1)
        self.checkBox_47 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_47.setObjectName("checkBox_47")
        self.gridLayout_2.addWidget(self.checkBox_47, 3, 4, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 12, 0, 1, 8)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 7, 0, 1, 4)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 3, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.lineEdit_soi = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_soi.setObjectName("lineEdit_soi")
        self.horizontalLayout_6.addWidget(self.lineEdit_soi)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 4, 3, 1, 3)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.checkBox_11 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_11.setObjectName("checkBox_11")
        self.horizontalLayout_12.addWidget(self.checkBox_11)
        self.checkBox_12 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_12.setObjectName("checkBox_12")
        self.horizontalLayout_12.addWidget(self.checkBox_12)
        self.checkBox_13 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_13.setObjectName("checkBox_13")
        self.horizontalLayout_12.addWidget(self.checkBox_13)
        self.gridLayout_3.addLayout(self.horizontalLayout_12, 10, 0, 1, 7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_10.addWidget(self.label_14)
        self.lineEdit_state = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_state.setText("")
        self.lineEdit_state.setObjectName("lineEdit_state")
        self.horizontalLayout_10.addWidget(self.lineEdit_state)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 6, 0, 1, 5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_8.addWidget(self.label_17)
        self.lineEdit_district = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_district.setObjectName("lineEdit_district")
        self.horizontalLayout_8.addWidget(self.lineEdit_district)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 5, 0, 1, 5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.lineEdit_street = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_street.setObjectName("lineEdit_street")
        self.horizontalLayout_7.addWidget(self.lineEdit_street)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 4, 6, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.scrollAreaWidgetContents)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 13, 4, 1, 3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Edit Profile", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("Form", "PLEASE CHECK ALL THAT APPLY TO YOUR BUSINESS", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "Company name:", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("Form", "City/Ampur:", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("Form", " Zip Code:", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Form", "No.", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "Tel :", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "Website :", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("Form", "If LLC please check Federal tax filing type", None, -1))
        self.label_comp_logo.setText(QtWidgets.QApplication.translate("Form", "Company logo", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("Form", "Add Logo", None, -1))
        self.checkBox.setText(QtWidgets.QApplication.translate("Form", "Sole Proprietor", None, -1))
        self.checkBox_2.setText(QtWidgets.QApplication.translate("Form", "Association", None, -1))
        self.checkBox_3.setText(QtWidgets.QApplication.translate("Form", "LLLP", None, -1))
        self.checkBox_4.setText(QtWidgets.QApplication.translate("Form", "Limited Liability Partnership", None, -1))
        self.checkBox_5.setText(QtWidgets.QApplication.translate("Form", "Government Entity", None, -1))
        self.checkBox_7.setText(QtWidgets.QApplication.translate("Form", "Limited Partnership", None, -1))
        self.checkBox_8.setText(QtWidgets.QApplication.translate("Form", "Partnership", None, -1))
        self.checkBox_9.setText(QtWidgets.QApplication.translate("Form", "Limited Liability Company", None, -1))
        self.checkBox_6.setText(QtWidgets.QApplication.translate("Form", "Corporation", None, -1))
        self.checkBox_10.setText(QtWidgets.QApplication.translate("Form", "Other", None, -1))
        self.checkBox_24.setText(QtWidgets.QApplication.translate("Form", "Hazardous Material", None, -1))
        self.checkBox_31.setText(QtWidgets.QApplication.translate("Form", "Retail Sales—New", None, -1))
        self.checkBox_23.setText(QtWidgets.QApplication.translate("Form", "Service", None, -1))
        self.checkBox_21.setText(QtWidgets.QApplication.translate("Form", "Alcohol", None, -1))
        self.checkBox_17.setText(QtWidgets.QApplication.translate("Form", "Water Appropriation", None, -1))
        self.checkBox_39.setText(QtWidgets.QApplication.translate("Form", "Transportation", None, -1))
        self.checkBox_40.setText(QtWidgets.QApplication.translate("Form", "Banker", None, -1))
        self.checkBox_29.setText(QtWidgets.QApplication.translate("Form", "Manufacturing", None, -1))
        self.checkBox_33.setText(QtWidgets.QApplication.translate("Form", "Construction/Erection", None, -1))
        self.checkBox_41.setText(QtWidgets.QApplication.translate("Form", "Tire Sales", None, -1))
        self.checkBox_37.setText(QtWidgets.QApplication.translate("Form", "Health Services", None, -1))
        self.checkBox_14.setText(QtWidgets.QApplication.translate("Form", "Mining", None, -1))
        self.checkBox_26.setText(QtWidgets.QApplication.translate("Form", "Financial Institutions", None, -1))
        self.checkBox_15.setText(QtWidgets.QApplication.translate("Form", "Domestics", None, -1))
        self.checkBox_22.setText(QtWidgets.QApplication.translate("Form", "Agriculture", None, -1))
        self.checkBox_36.setText(QtWidgets.QApplication.translate("Form", "Delivery", None, -1))
        self.checkBox_47.setText(QtWidgets.QApplication.translate("Form", "Other", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("Form", "Legal Entity Type", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("Form", "Address", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Form", "Soi:", None, -1))
        self.checkBox_11.setText(QtWidgets.QApplication.translate("Form", "Corporation", None, -1))
        self.checkBox_12.setText(QtWidgets.QApplication.translate("Form", "Sole Proprietor", None, -1))
        self.checkBox_13.setText(QtWidgets.QApplication.translate("Form", "Partnership", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("Form", "Province/State:", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("Form", "District/Tambon:", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("Form", "Street:", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

