# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Company_Edit_Profile.ui',
# licensing of 'Company_Edit_Profile.ui' applies.
#
# Created: Fri May 31 17:33:15 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(783, 599)
        Form.setStyleSheet("QWidget{\n"
"    background-color: rgb(60,60,60);\n"
"    color: white\n"
"}\n"
"\n"
"QComboBox{\n"
"    \n"
"    background-color: rgb(65, 65, 65);\n"
"}"
'''QLabel#error_label{\n
    color: rgb(190,30,30);
}
''')
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 759, 575))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.lineEdit_houseNo = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_houseNo.setObjectName("lineEdit_houseNo")
        self.horizontalLayout_5.addWidget(self.lineEdit_houseNo)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_OK = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.horizontalLayout_13.addWidget(self.pushButton_OK)
        self.pushButton_Cancle = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_Cancle.setObjectName("pushButton_Cancle")
        self.horizontalLayout_13.addWidget(self.pushButton_Cancle)
        self.gridLayout_3.addLayout(self.horizontalLayout_13, 13, 3, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_8.addWidget(self.label_17)
        self.lineEdit_district = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_district.setObjectName("lineEdit_district")
        self.horizontalLayout_8.addWidget(self.lineEdit_district)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 5, 0, 1, 4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.lineEdit_city = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_city.setText("")
        self.lineEdit_city.setObjectName("lineEdit_city")
        self.horizontalLayout_9.addWidget(self.lineEdit_city)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 5, 4, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_comp_name = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_comp_name.setText("")
        self.lineEdit_comp_name.setObjectName("lineEdit_comp_name")
        self.horizontalLayout.addWidget(self.lineEdit_comp_name)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_tel = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_tel.setObjectName("lineEdit_tel")
        self.horizontalLayout_3.addWidget(self.lineEdit_tel)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(98, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_web = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_web.setText("")
        self.lineEdit_web.setObjectName("lineEdit_web")
        self.horizontalLayout_4.addWidget(self.lineEdit_web)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 2, 0, 1, 7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.lineEdit_soi = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_soi.setObjectName("lineEdit_soi")
        self.horizontalLayout_6.addWidget(self.lineEdit_soi)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 4, 2, 1, 3)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 0, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 13, 6, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.lineEdit_street = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_street.setObjectName("lineEdit_street")
        self.horizontalLayout_7.addWidget(self.lineEdit_street)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 4, 5, 1, 2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_10.addWidget(self.label_14)
        self.lineEdit_state = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_state.setText("")
        self.lineEdit_state.setObjectName("lineEdit_state")
        self.horizontalLayout_10.addWidget(self.lineEdit_state)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 6, 0, 1, 4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_comp_logo = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_comp_logo.setObjectName("label_comp_logo")
        self.horizontalLayout_2.addWidget(self.label_comp_logo)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 6, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_11.addWidget(self.label_16)
        self.lineEdit_zip = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_zip.setObjectName("lineEdit_zip")
        self.horizontalLayout_11.addWidget(self.lineEdit_zip)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 6, 4, 1, 3)
        self.error_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.gridLayout_3.addWidget(self.error_label, 11, 3, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        self.comboBox_Business = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_Business.setObjectName("comboBox_Business")
        self.comboBox_Business.addItem("")
        self.comboBox_Business.addItem("")
        self.comboBox_Business.addItem("")
        self.comboBox_Business.addItem("")
        self.comboBox_Business.addItem("")
        self.comboBox_Business.addItem("")
        self.comboBox_Business.addItem("")
        self.comboBox_Business.addItem("")
        self.comboBox_Business.addItem("")
        self.comboBox_Business.addItem("")
        self.comboBox_Business.addItem("")
        self.comboBox_Business.addItem("")
        self.horizontalLayout_12.addWidget(self.comboBox_Business)
        self.gridLayout_3.addLayout(self.horizontalLayout_12, 10, 3, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Form", "No.", None, -1))
        self.pushButton_OK.setText(QtWidgets.QApplication.translate("Form", "OK", None, -1))
        self.pushButton_Cancle.setText(QtWidgets.QApplication.translate("Form", "Cancle", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("Form", "District/Tambon:", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("Form", "City/Ampur:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "Company name:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "Tel :", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "E-mail :", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Form", "Soi:", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Edit Profile", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("Form", "Address", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("Form", "Street:", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("Form", "Province/State:", None, -1))
        self.label_comp_logo.setText(QtWidgets.QApplication.translate("Form", "Company logo", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("Form", "Add Logo", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("Form", " Zip Code:", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "Company business type", None, -1))
        self.comboBox_Business.setItemText(0, QtWidgets.QApplication.translate("Form", "  -- None --", None, -1))
        self.comboBox_Business.setItemText(1, QtWidgets.QApplication.translate("Form", "New Item", None, -1))
        self.comboBox_Business.setItemText(2, QtWidgets.QApplication.translate("Form", "Alocohol", None, -1))
        self.comboBox_Business.setItemText(3, QtWidgets.QApplication.translate("Form", "Construction", None, -1))
        self.comboBox_Business.setItemText(4, QtWidgets.QApplication.translate("Form", "Domestic", None, -1))
        self.comboBox_Business.setItemText(5, QtWidgets.QApplication.translate("Form", "Financial instructor", None, -1))
        self.comboBox_Business.setItemText(6, QtWidgets.QApplication.translate("Form", "Health Service", None, -1))
        self.comboBox_Business.setItemText(7, QtWidgets.QApplication.translate("Form", "Manufacturer", None, -1))
        self.comboBox_Business.setItemText(8, QtWidgets.QApplication.translate("Form", "Mining", None, -1))
        self.comboBox_Business.setItemText(9, QtWidgets.QApplication.translate("Form", "Retail sales", None, -1))
        self.comboBox_Business.setItemText(10, QtWidgets.QApplication.translate("Form", "Service", None, -1))
        self.comboBox_Business.setItemText(11, QtWidgets.QApplication.translate("Form", "Transportation", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

