# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Edit_Create_User_Profile.ui',
# licensing of 'Edit_Create_User_Profile.ui' applies.
#
# Created: Thu May 30 11:45:39 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(576, 690)
        Form.setStyleSheet("QWidget{\n"
"    background-color: rgb(60, 60, 60);\n"
"    font: \"Arial\";\n"
"    color: white\n""}\n"
"\n"
"QComboBox{    \n"
"    background-color: rgb(65, 65, 65);\n"
"}url(:/bg/grey.png)")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(180, 10, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(30, 180, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(30, 320, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(30, 350, 101, 20))
        self.label_18.setObjectName("label_18")
        self.comboBox_degree = QtWidgets.QComboBox(Form)
        self.comboBox_degree.setGeometry(QtCore.QRect(30, 380, 121, 22))
        self.comboBox_degree.setObjectName("comboBox_degree")
        self.comboBox_degree.addItem("")
        self.comboBox_degree.addItem("")
        self.comboBox_degree.addItem("")
        self.comboBox_degree.addItem("")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(180, 350, 101, 20))
        self.label_19.setObjectName("label_19")
        self.listWidget_ED_background = QtWidgets.QListWidget(Form)
        self.listWidget_ED_background.setGeometry(QtCore.QRect(20, 480, 521, 131))
        self.listWidget_ED_background.setObjectName("listWidget_ED_background")
        self.pushButton_cancle_profile = QtWidgets.QPushButton(Form)
        self.pushButton_cancle_profile.setGeometry(QtCore.QRect(170, 640, 75, 23))
        self.pushButton_cancle_profile.setObjectName("pushButton_cancle_profile")
        self.pushButton_confirm_profile = QtWidgets.QPushButton(Form)
        self.pushButton_confirm_profile.setGeometry(QtCore.QRect(300, 640, 75, 23))
        self.pushButton_confirm_profile.setObjectName("pushButton_confirm_profile")
        self.comboBox_subject = QtWidgets.QComboBox(Form)
        self.comboBox_subject.setGeometry(QtCore.QRect(180, 380, 161, 22))
        self.comboBox_subject.setObjectName("comboBox_subject")
        self.comboBox_subject.addItem("")
        self.comboBox_subject.addItem("")
        self.comboBox_subject.addItem("")
        self.comboBox_subject.addItem("")
        self.comboBox_subject.addItem("")
        self.comboBox_subject.addItem("")
        self.comboBox_subject.addItem("")
        self.comboBox_subject.addItem("")
        self.comboBox_subject.addItem("")
        self.comboBox_subject.addItem("")
        self.comboBox_subject.addItem("")
        self.comboBox_subject.addItem("")
        self.comboBox_subject.addItem("")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 140, 21, 24))
        self.label_5.setObjectName("label_5")
        self.lineEdit_userTel = QtWidgets.QLineEdit(Form)
        self.lineEdit_userTel.setGeometry(QtCore.QRect(70, 140, 141, 22))
        self.lineEdit_userTel.setObjectName("lineEdit_userTel")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 38, 24))
        self.label_2.setObjectName("label_2")
        self.lineEdit_name = QtWidgets.QLineEdit(Form)
        self.lineEdit_name.setGeometry(QtCore.QRect(70, 110, 141, 22))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(230, 140, 41, 24))
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(230, 110, 57, 24))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(450, 110, 27, 24))
        self.label_4.setObjectName("label_4")
        self.lineEdit_name_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_name_2.setGeometry(QtCore.QRect(290, 110, 141, 22))
        self.lineEdit_name_2.setObjectName("lineEdit_name_2")
        self.lineEdit_name_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_name_3.setGeometry(QtCore.QRect(290, 140, 141, 22))
        self.lineEdit_name_3.setObjectName("lineEdit_name_3")
        self.lineEdit_name_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_name_4.setGeometry(QtCore.QRect(490, 110, 31, 22))
        self.lineEdit_name_4.setObjectName("lineEdit_name_4")
        self.lineEdit_houseNo = QtWidgets.QLineEdit(Form)
        self.lineEdit_houseNo.setGeometry(QtCore.QRect(60, 210, 63, 22))
        self.lineEdit_houseNo.setObjectName("lineEdit_houseNo")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(30, 210, 31, 24))
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(140, 210, 23, 24))
        self.label_10.setObjectName("label_10")
        self.lineEdit_soi = QtWidgets.QLineEdit(Form)
        self.lineEdit_soi.setGeometry(QtCore.QRect(170, 210, 121, 22))
        self.lineEdit_soi.setObjectName("lineEdit_soi")
        self.lineEdit_street = QtWidgets.QLineEdit(Form)
        self.lineEdit_street.setGeometry(QtCore.QRect(360, 210, 126, 22))
        self.lineEdit_street.setObjectName("lineEdit_street")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(310, 210, 51, 24))
        self.label_11.setObjectName("label_11")
        self.lineEdit_district = QtWidgets.QLineEdit(Form)
        self.lineEdit_district.setGeometry(QtCore.QRect(130, 240, 117, 22))
        self.lineEdit_district.setObjectName("lineEdit_district")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(30, 240, 101, 24))
        self.label_12.setObjectName("label_12")
        self.lineEdit_city = QtWidgets.QLineEdit(Form)
        self.lineEdit_city.setGeometry(QtCore.QRect(340, 240, 124, 22))
        self.lineEdit_city.setText("")
        self.lineEdit_city.setObjectName("lineEdit_city")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(260, 240, 71, 24))
        self.label_13.setObjectName("label_13")
        self.lineEdit_state = QtWidgets.QLineEdit(Form)
        self.lineEdit_state.setGeometry(QtCore.QRect(130, 270, 94, 22))
        self.lineEdit_state.setText("")
        self.lineEdit_state.setObjectName("lineEdit_state")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(30, 270, 91, 24))
        self.label_14.setObjectName("label_14")
        self.lineEdit_zip = QtWidgets.QLineEdit(Form)
        self.lineEdit_zip.setGeometry(QtCore.QRect(310, 270, 63, 22))
        self.lineEdit_zip.setObjectName("lineEdit_zip")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(240, 270, 61, 24))
        self.label_15.setObjectName("label_15")
        self.lineEdit_homeTel = QtWidgets.QLineEdit(Form)
        self.lineEdit_homeTel.setGeometry(QtCore.QRect(420, 270, 129, 22))
        self.lineEdit_homeTel.setText("")
        self.lineEdit_homeTel.setObjectName("lineEdit_homeTel")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(390, 270, 31, 24))
        self.label_16.setObjectName("label_16")
        self.comboBox_subject_2 = QtWidgets.QComboBox(Form)
        self.comboBox_subject_2.setGeometry(QtCore.QRect(180, 410, 161, 22))
        self.comboBox_subject_2.setObjectName("comboBox_subject_2")
        self.comboBox_subject_2.addItem("")
        self.comboBox_subject_2.addItem("")
        self.comboBox_subject_2.addItem("")
        self.comboBox_subject_2.addItem("")
        self.comboBox_subject_2.addItem("")
        self.comboBox_subject_2.addItem("")
        self.comboBox_subject_2.addItem("")
        self.comboBox_subject_2.addItem("")
        self.comboBox_subject_2.addItem("")
        self.comboBox_subject_2.addItem("")
        self.comboBox_subject_2.addItem("")
        self.comboBox_subject_2.addItem("")
        self.comboBox_subject_2.addItem("")
        self.register_language = QtWidgets.QComboBox(Form)
        self.register_language.setGeometry(QtCore.QRect(370, 380, 91, 22))
        self.register_language.setObjectName("register_language")
        self.register_language.addItem("")
        self.register_language.addItem("")
        self.register_language.addItem("")
        self.register_language.addItem("")
        self.register_language.addItem("")
        self.register_language.addItem("")
        self.register_language.addItem("")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(370, 350, 101, 20))
        self.label_20.setObjectName("label_20")
        self.register_language_2 = QtWidgets.QComboBox(Form)
        self.register_language_2.setGeometry(QtCore.QRect(370, 410, 91, 22))
        self.register_language_2.setObjectName("register_language_2")
        self.register_language_2.addItem("")
        self.register_language_2.addItem("")
        self.register_language_2.addItem("")
        self.register_language_2.addItem("")
        self.register_language_2.addItem("")
        self.register_language_2.addItem("")
        self.register_language_2.addItem("")
        self.comboBox_subject_3 = QtWidgets.QComboBox(Form)
        self.comboBox_subject_3.setGeometry(QtCore.QRect(180, 440, 161, 22))
        self.comboBox_subject_3.setObjectName("comboBox_subject_3")
        self.comboBox_subject_3.addItem("")
        self.comboBox_subject_3.addItem("")
        self.comboBox_subject_3.addItem("")
        self.comboBox_subject_3.addItem("")
        self.comboBox_subject_3.addItem("")
        self.comboBox_subject_3.addItem("")
        self.comboBox_subject_3.addItem("")
        self.comboBox_subject_3.addItem("")
        self.comboBox_subject_3.addItem("")
        self.comboBox_subject_3.addItem("")
        self.comboBox_subject_3.addItem("")
        self.comboBox_subject_3.addItem("")
        self.comboBox_subject_3.addItem("")
        self.register_language_3 = QtWidgets.QComboBox(Form)
        self.register_language_3.setGeometry(QtCore.QRect(370, 440, 91, 22))
        self.register_language_3.setObjectName("register_language_3")
        self.register_language_3.addItem("")
        self.register_language_3.addItem("")
        self.register_language_3.addItem("")
        self.register_language_3.addItem("")
        self.register_language_3.addItem("")
        self.register_language_3.addItem("")
        self.register_language_3.addItem("")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Edit Profile", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Form", "Address", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("Form", "Education Background", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("Form", "Education degree:", None, -1))
        self.comboBox_degree.setItemText(0, QtWidgets.QApplication.translate("Form", "Associate degree ", None, -1))
        self.comboBox_degree.setItemText(1, QtWidgets.QApplication.translate("Form", "Bachelor\'s degree ", None, -1))
        self.comboBox_degree.setItemText(2, QtWidgets.QApplication.translate("Form", "Master\'s degree", None, -1))
        self.comboBox_degree.setItemText(3, QtWidgets.QApplication.translate("Form", "Doctoral degree", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("Form", "Subject:", None, -1))
        self.pushButton_cancle_profile.setText(QtWidgets.QApplication.translate("Form", "Cancle", None, -1))
        self.pushButton_confirm_profile.setText(QtWidgets.QApplication.translate("Form", "Confirm", None, -1))
        self.comboBox_subject.setItemText(0, QtWidgets.QApplication.translate("Form", " -- None --", None, -1))
        self.comboBox_subject.setItemText(1, QtWidgets.QApplication.translate("Form", "Accounting", None, -1))
        self.comboBox_subject.setItemText(2, QtWidgets.QApplication.translate("Form", "Computer Science", None, -1))
        self.comboBox_subject.setItemText(3, QtWidgets.QApplication.translate("Form", "Engineering", None, -1))
        self.comboBox_subject.setItemText(4, QtWidgets.QApplication.translate("Form", "Business Administration", None, -1))
        self.comboBox_subject.setItemText(5, QtWidgets.QApplication.translate("Form", "Sociology/Social Work", None, -1))
        self.comboBox_subject.setItemText(6, QtWidgets.QApplication.translate("Form", "Mathematics/Statistics", None, -1))
        self.comboBox_subject.setItemText(7, QtWidgets.QApplication.translate("Form", "Psychology", None, -1))
        self.comboBox_subject.setItemText(8, QtWidgets.QApplication.translate("Form", "History/Political Science", None, -1))
        self.comboBox_subject.setItemText(9, QtWidgets.QApplication.translate("Form", "Healthcare", None, -1))
        self.comboBox_subject.setItemText(10, QtWidgets.QApplication.translate("Form", "Education", None, -1))
        self.comboBox_subject.setItemText(11, QtWidgets.QApplication.translate("Form", "Environmental Science", None, -1))
        self.comboBox_subject.setItemText(12, QtWidgets.QApplication.translate("Form", "Visual & Performing Arts", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "Tel:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "Name:", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Form", "E-mail:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "Surname:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "Age:", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Form", "No.", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Form", "Soi:", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Form", "Street:", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("Form", "District/Tambon:", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("Form", "City/Ampur:", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("Form", "Province/State:", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("Form", " Zip Code:", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("Form", "Tel:", None, -1))
        self.comboBox_subject_2.setItemText(0, QtWidgets.QApplication.translate("Form", " -- None --", None, -1))
        self.comboBox_subject_2.setItemText(1, QtWidgets.QApplication.translate("Form", "Accounting", None, -1))
        self.comboBox_subject_2.setItemText(2, QtWidgets.QApplication.translate("Form", "Computer Science", None, -1))
        self.comboBox_subject_2.setItemText(3, QtWidgets.QApplication.translate("Form", "Engineering", None, -1))
        self.comboBox_subject_2.setItemText(4, QtWidgets.QApplication.translate("Form", "Business Administration", None, -1))
        self.comboBox_subject_2.setItemText(5, QtWidgets.QApplication.translate("Form", "Sociology/Social Work", None, -1))
        self.comboBox_subject_2.setItemText(6, QtWidgets.QApplication.translate("Form", "Mathematics/Statistics", None, -1))
        self.comboBox_subject_2.setItemText(7, QtWidgets.QApplication.translate("Form", "Psychology", None, -1))
        self.comboBox_subject_2.setItemText(8, QtWidgets.QApplication.translate("Form", "History/Political Science", None, -1))
        self.comboBox_subject_2.setItemText(9, QtWidgets.QApplication.translate("Form", "Healthcare", None, -1))
        self.comboBox_subject_2.setItemText(10, QtWidgets.QApplication.translate("Form", "Education", None, -1))
        self.comboBox_subject_2.setItemText(11, QtWidgets.QApplication.translate("Form", "Environmental Science", None, -1))
        self.comboBox_subject_2.setItemText(12, QtWidgets.QApplication.translate("Form", "Visual & Performing Arts", None, -1))
        self.register_language.setItemText(0, QtWidgets.QApplication.translate("Form", " -- None -- ", None, -1))
        self.register_language.setItemText(1, QtWidgets.QApplication.translate("Form", "English", None, -1))
        self.register_language.setItemText(2, QtWidgets.QApplication.translate("Form", "Thai", None, -1))
        self.register_language.setItemText(3, QtWidgets.QApplication.translate("Form", "Chinese", None, -1))
        self.register_language.setItemText(4, QtWidgets.QApplication.translate("Form", "Spanish", None, -1))
        self.register_language.setItemText(5, QtWidgets.QApplication.translate("Form", "Japanese", None, -1))
        self.register_language.setItemText(6, QtWidgets.QApplication.translate("Form", "Korea", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("Form", "Language :", None, -1))
        self.register_language_2.setItemText(0, QtWidgets.QApplication.translate("Form", " -- None -- ", None, -1))
        self.register_language_2.setItemText(1, QtWidgets.QApplication.translate("Form", "English", None, -1))
        self.register_language_2.setItemText(2, QtWidgets.QApplication.translate("Form", "Thai", None, -1))
        self.register_language_2.setItemText(3, QtWidgets.QApplication.translate("Form", "Chinese", None, -1))
        self.register_language_2.setItemText(4, QtWidgets.QApplication.translate("Form", "Spanish", None, -1))
        self.register_language_2.setItemText(5, QtWidgets.QApplication.translate("Form", "Japanese", None, -1))
        self.register_language_2.setItemText(6, QtWidgets.QApplication.translate("Form", "Korea", None, -1))
        self.comboBox_subject_3.setItemText(0, QtWidgets.QApplication.translate("Form", " -- None --", None, -1))
        self.comboBox_subject_3.setItemText(1, QtWidgets.QApplication.translate("Form", "Accounting", None, -1))
        self.comboBox_subject_3.setItemText(2, QtWidgets.QApplication.translate("Form", "Computer Science", None, -1))
        self.comboBox_subject_3.setItemText(3, QtWidgets.QApplication.translate("Form", "Engineering", None, -1))
        self.comboBox_subject_3.setItemText(4, QtWidgets.QApplication.translate("Form", "Business Administration", None, -1))
        self.comboBox_subject_3.setItemText(5, QtWidgets.QApplication.translate("Form", "Sociology/Social Work", None, -1))
        self.comboBox_subject_3.setItemText(6, QtWidgets.QApplication.translate("Form", "Mathematics/Statistics", None, -1))
        self.comboBox_subject_3.setItemText(7, QtWidgets.QApplication.translate("Form", "Psychology", None, -1))
        self.comboBox_subject_3.setItemText(8, QtWidgets.QApplication.translate("Form", "History/Political Science", None, -1))
        self.comboBox_subject_3.setItemText(9, QtWidgets.QApplication.translate("Form", "Healthcare", None, -1))
        self.comboBox_subject_3.setItemText(10, QtWidgets.QApplication.translate("Form", "Education", None, -1))
        self.comboBox_subject_3.setItemText(11, QtWidgets.QApplication.translate("Form", "Environmental Science", None, -1))
        self.comboBox_subject_3.setItemText(12, QtWidgets.QApplication.translate("Form", "Visual & Performing Arts", None, -1))
        self.register_language_3.setItemText(0, QtWidgets.QApplication.translate("Form", " -- None -- ", None, -1))
        self.register_language_3.setItemText(1, QtWidgets.QApplication.translate("Form", "English", None, -1))
        self.register_language_3.setItemText(2, QtWidgets.QApplication.translate("Form", "Thai", None, -1))
        self.register_language_3.setItemText(3, QtWidgets.QApplication.translate("Form", "Chinese", None, -1))
        self.register_language_3.setItemText(4, QtWidgets.QApplication.translate("Form", "Spanish", None, -1))
        self.register_language_3.setItemText(5, QtWidgets.QApplication.translate("Form", "Japanese", None, -1))
        self.register_language_3.setItemText(6, QtWidgets.QApplication.translate("Form", "Korea", None, -1))

# import source_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

